/**
 * Skrip DDL Schema Database Sehatin sesuai ERD Tugas Kelompok 7
 * Anda dapat menjalankan skrip SQL ini langsung di Supabase SQL Editor
 * atau menggunakan database runner jika DATABASE_URL disediakan.
 */
const { sql } = require("./db");

const schemaSql = `
-- 1. Table SERVICES (Layanan Medis)
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table PATIENTS (Pasien)
CREATE TABLE IF NOT EXISTS patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_rm VARCHAR(50) UNIQUE NOT NULL,
  nik VARCHAR(20) UNIQUE NOT NULL,
  nama_lengkap VARCHAR(255) NOT NULL,
  jenis_kelamin VARCHAR(20) NOT NULL,
  tanggal_lahir DATE NOT NULL,
  no_telp VARCHAR(20),
  alamat TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table DOCTORS (Dokter)
CREATE TABLE IF NOT EXISTS doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_dokter VARCHAR(255) NOT NULL,
  spesialisasi VARCHAR(100) NOT NULL,
  no_sip VARCHAR(100) UNIQUE,
  no_telp VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table DOCTOR_SCHEDULES (Jadwal Dokter)
CREATE TABLE IF NOT EXISTS doctor_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
  hari VARCHAR(20) NOT NULL,
  jam_mulai TIME NOT NULL,
  jam_selesai TIME NOT NULL,
  kuota INT DEFAULT 10,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table APPOINTMENTS (Reservasi / Janji Temu)
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  doctor_id BIGINT NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
  service_id BIGINT REFERENCES services(id) ON DELETE SET NULL,
  tanggal_kunjungan DATE NOT NULL,
  jam_kunjungan TIME NOT NULL,
  keluhan TEXT,
  status VARCHAR(50) DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Table MEDICAL_RECORDS (Rekam Medis)
CREATE TABLE IF NOT EXISTS medical_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT UNIQUE NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  doctor_id BIGINT NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
  diagnosa TEXT NOT NULL,
  tindakan TEXT,
  resep_obat TEXT,
  tanggal_periksa TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Table INVOICES (Tagihan & Pembayaran)
CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id BIGINT UNIQUE NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  no_invoice VARCHAR(50) UNIQUE NOT NULL,
  total_bayar NUMERIC(12, 2) NOT NULL DEFAULT 0,
  metode VARCHAR(50),
  status VARCHAR(50) DEFAULT 'unpaid',
  tanggal_bayar TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
`;

async function createSchema() {
  if (!sql) {
    console.log(
      "Catatan: DATABASE_URL belum diatur di .env. Anda dapat meng-copy query SQL di bawah ini dan menjalankannya di Supabase Dashboard -> SQL Editor:\n"
    );
    console.log(schemaSql);
    return;
  }

  try {
    console.log("Menjalankan migrasi schema ke PostgreSQL...");
    await sql.unsafe(schemaSql);
    console.log("Migrasi schema berhasil diselesaikan!");
  } catch (err) {
    console.error("Gagal menjalankan migrasi schema:", err.message);
  } finally {
    if (sql) await sql.end();
  }
}

if (require.main === module) {
  createSchema();
}

module.exports = { schemaSql, createSchema };
